In [23]:
import torch.nn as nn
import torch

In [24]:
A = torch.tensor([1,2,3])

In [25]:
embedding = nn.Embedding(10, 3)

In [26]:
embedding(A)

tensor([[-0.1441, -2.6497, -0.0610],
        [ 1.4158, -1.1405, -0.8985],
        [-0.5867, -0.5864, -0.7786]], grad_fn=<EmbeddingBackward>)

In [35]:
pretrained_embeddings = torch.tensor([[0.1*i for k in range(3)] for i in range(10)])

In [36]:
pretrained_embeddings

tensor([[0.0000, 0.0000, 0.0000],
        [0.1000, 0.1000, 0.1000],
        [0.2000, 0.2000, 0.2000],
        [0.3000, 0.3000, 0.3000],
        [0.4000, 0.4000, 0.4000],
        [0.5000, 0.5000, 0.5000],
        [0.6000, 0.6000, 0.6000],
        [0.7000, 0.7000, 0.7000],
        [0.8000, 0.8000, 0.8000],
        [0.9000, 0.9000, 0.9000]])

In [34]:
_ = embedding.weight.data.copy_(pretrained_embeddings)

RuntimeError: The expanded size of the tensor (10) must match the existing size (20) at non-singleton dimension 0.  Target sizes: [10, 3].  Tensor sizes: [20, 3]

In [30]:
embedding(A)

tensor([[0.1000, 0.1000, 0.1000],
        [0.2000, 0.2000, 0.2000],
        [0.3000, 0.3000, 0.3000]], grad_fn=<EmbeddingBackward>)

In [38]:
class Model(nn.Module):
    def __init__(self, vocabulary_size,input_dim_audio, embedding_dim, output_dim):
        super(Model, self).__init__()
        self.vocabulary_size = vocabulary_size
        self.input_dim_audio = input_dim_audio
        self.embedding_dim = embedding_dim
        self.output_dim = output_dim

        self.embedding = nn.Embedding(vocabulary_size, embedding_dim)


    def forward(self, data):
        text = data[0]
        audio = data[1]

        embedded = self.embedding(text)
        return embedded

In [39]:
mod = Model(100,20,300,10)

In [40]:
input = torch.randn(20, 16, 50)

tensor([[[ 1.6243e+00,  4.7961e-02,  5.2408e-01,  ..., -1.3543e+00,
           1.1764e+00, -1.8711e+00],
         [-8.1210e-01, -8.0798e-01, -4.3334e-01,  ..., -1.5408e-01,
          -2.0409e+00,  1.0447e+00],
         [-5.6067e-01, -1.7007e+00, -7.2215e-01,  ..., -9.6397e-01,
           2.1561e-02,  7.1909e-01],
         ...,
         [-3.5136e-01, -1.2038e+00, -2.8032e+00,  ..., -1.6382e+00,
           5.3726e-01, -7.6472e-01],
         [-3.8739e-01,  3.4711e-01, -2.7452e-01,  ..., -1.1566e+00,
          -3.4068e-01, -1.5947e+00],
         [ 1.3566e+00,  8.6383e-02,  9.6290e-01,  ...,  1.0812e+00,
          -1.3943e+00,  4.7307e-02]],

        [[-1.1724e-01,  1.2570e+00, -9.8797e-01,  ...,  1.4980e+00,
          -1.3136e+00, -2.6921e-01],
         [-8.7407e-02, -8.0296e-01, -1.8132e+00,  ...,  7.5152e-01,
          -5.7830e-01, -7.6128e-01],
         [ 1.6377e-01, -5.7366e-01,  4.1530e-01,  ...,  1.6107e-01,
           1.2040e+00, -4.7993e-01],
         ...,
         [ 7.2963e-01, -1